python:
  - "3.8"
 # - "3.6"      # current default Python on Travis CI
 # - "3.7"
  
# command to install dependencies
install:
  #- apt-get install python3-pip -y
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest